name: Continuous Integration
on: [pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout cplace-asc
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 18.19.1

            - name: Cache Node Modules
              id: npm-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install modules
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Formatter
              run: npm run prettier-check

            - name: Run Jest
              run: node_modules/.bin/jest --verbose

    compile:
        env:
            ENV_CPLACE_ARTIFACTORY_ACTOR: ${{ secrets.ENV_CPLACE_ARTIFACTORY_ACTOR }}
            ENV_CPLACE_ARTIFACTORY_TOKEN: ${{ secrets.ENV_CPLACE_ARTIFACTORY_TOKEN }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                node_version:
                    - 18.19.1
        name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout cplace-asc
              uses: actions/checkout@v4

            - name: Checkout cplace
              uses: actions/checkout@v4
              with:
                  repository: collaborationFactory/cplace
                  ref: 'release/23.4'
                  path: main
                  token: ${{ secrets.CPLACE_GITHUB_TOKEN }}

            - name: Checkout cplace-project-planning
              uses: actions/checkout@v4
              with:
                  repository: collaborationFactory/cplace-project-planning
                  ref: 'release/23.4'
                  path: cplace-project-planning
                  token: ${{ secrets.CPLACE_GITHUB_TOKEN }}

            - name: Checkout cplace-paw
              uses: actions/checkout@v4
              with:
                  repository: collaborationFactory/cplace-paw
                  ref: 'release/23.4'
                  path: cplace-paw
                  token: ${{ secrets.CPLACE_GITHUB_TOKEN }}

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}

            - name: Cache Node Modules
              id: npm-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install modules
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'adopt'
                  java-version: '17'

            - name: Create plugin descriptors in main
              working-directory: ./main
              run: ./gradlew generatePluginDescriptor

            - name: Create plugin descriptors cplace-project-planning
              working-directory: ./cplace-project-planning
              run: ./gradlew generatePluginDescriptor

            - name: Create plugin descriptors cplace-paw
              working-directory: ./cplace-paw
              run: ./gradlew generatePluginDescriptor

            - name: Build
              run: npm run test-build

            - name: cplace-asc main
              working-directory: ./main
              timeout-minutes: 20
              run: |
                  npm i ../dist//cplace-global-registry-initializer-0.0.0-SNAPSHOT.tgz -D
                  npm i ../dist/cplace-asc-local-0.0.0-SNAPSHOT.tgz -D
                  chmod 777 node_modules/.bin/cplace-asc
                  node_modules/.bin/cplace-asc --production --clean

            - name: cplace-asc cplace-paw
              working-directory: ./cplace-paw
              timeout-minutes: 20
              run: |
                  npm i ../dist//cplace-global-registry-initializer-0.0.0-SNAPSHOT.tgz -D
                  npm i ../dist/cplace-asc-local-0.0.0-SNAPSHOT.tgz -D
                  chmod 777 node_modules/.bin/cplace-asc
                  node_modules/.bin/cplace-asc --production --clean

            - name: cplace-asc cplace-project-planning
              working-directory: ./cplace-project-planning
              timeout-minutes: 20
              run: |
                  npm i ../dist//cplace-global-registry-initializer-0.0.0-SNAPSHOT.tgz -D
                  npm i ../dist/cplace-asc-local-0.0.0-SNAPSHOT.tgz -D
                  chmod 777 node_modules/.bin/cplace-asc
                  node_modules/.bin/cplace-asc --production --clean
