name: Continuous Integration
on: [pull_request]

jobs:
    test:
        name: Run unit tests with Jest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install modules
              run: npm ci
            - name: Build
              run: npm run prepare
            - name: Run Jest
              run: node_modules/.bin/jest --verbose
