name: Continuous Integration
on: [pull_request]

jobs:
    test:
        name: Test all
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Cache Node Modules
              id: npm-cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/npm-shrinkwrap.json') }}

            - name: Install modules
              run: npm ci

            - name: Prettier
              run: npm run prettier-check

            - name: Build
              run: npm run prepare

            - name: Run Jest
              run: node_modules/.bin/jest --verbose
