name: 'Publish CI'
on:
    push:
        tags:
            - 'v*.*.*'

env:
    NODE_ENV: 'production'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout cplace-asc
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Checkout latest tag
              run: |
                  LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                  git checkout $LATEST_TAG

            - uses: actions/setup-node@v1
              with:
                  node-version: '18.11.0'
                  registry-url: 'https://registry.npmjs.org'

            - name: Cache Node Modules
              id: npm-cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install modules
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Publish
              run: npx ts-node tools/publish.ts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
