name: 'Publish CI'
on:
    push:
        tags:
            - 'v*.*.*'
            - 'v0.0.0-*'

env:
    NODE_ENV: 'production'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}

            - name: Checkout cplace-asc
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get tag
              id: tag
              uses: dawidd6/action-get-tag@v1

            - uses: actions/setup-node@v4
              with:
                  node-version: '18.18.2'
                  registry-url: 'https://registry.npmjs.org'

            - name: Cache Node Modules
              id: npm-cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install modules
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Publish
              run: npx ts-node tools/scripts/publish.ts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  TAG: ${{ steps.tag.outputs.tag }}
